use_frameworks!

target 'ChartExample' do
  pod 'SwiftyJSON', '4.0.0'      # old version: '3.1.4'
  pod 'Charts', '3.1.1'          # old version: '3.0.3'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '4.1'    # old version: '3.0' 
    end
  end
end